---
apiVersion: v1
kind: Service
metadata:
  name: cluster-collector
  namespace: checkmk-monitoring
  labels:
    app: cluster-collector
spec:
  ports:
    - name: api
      port: 80
      targetPort: 10050
      protocol: TCP
  # If ingress is used:
  # type: LoadBalancer
  selector:
    app: cluster-collector
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-collector-nodeport
  namespace: checkmk-monitoring
  labels:
    app: cluster-collector
spec:
  type: NodePort
  ports:
    - name: cluster-collector
      port: 30035
      nodePort: 30035
      targetPort: 10050
      protocol: TCP
  selector:
    app: cluster-collector
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: checkmk-monitoring
  labels:
    app: node-collector-cadvisor
spec:
  ports:
    - name: cadvisor
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: node-collector-cadvisor
