---
{{- if .Values.clusterCollector.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "checkmk.fullname" . }}-cluster-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
  {{- with .Values.clusterCollector.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.clusterCollector.ingress.className }}
  ingressClassName: {{ .Values.clusterCollector.ingress.className }}
  {{- end }}
  {{- if .Values.clusterCollector.ingress.tls }}
  tls:
    {{- range .Values.clusterCollector.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.clusterCollector.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "checkmk.fullname" . }}-cluster-collector
                port:
                  number: {{ .Values.clusterCollector.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
